from pyteal import Int
from algosdk.encoding import decode_address, encode_address


BITSAVE_ADDRESS = 'IW543YK6N4P4VDFDDPWOADVIRGNFFDBYVWQ46NG4MT6QCFCFHDFBZQ35RA'
CS_TOKEN = Int(0)

# BITSAVE_ADDRESS = Addr('WUJY7U7G5CPZ6MB3LTJBUZ4UDRXQZA7OE77AD3X4PHAHBHQKQX5DXE5RSI')
